/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcularviagem2;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Etec-User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAutonomia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValorComb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTempoViagem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVelocidade = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("Autonomia");

        txtAutonomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutonomiaActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor do combustível");

        jLabel3.setText("Duração da viagem");

        jLabel4.setText("Velocidade média do veículo");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAutonomia)
                    .addComponent(txtValorComb)
                    .addComponent(txtTempoViagem)
                    .addComponent(txtVelocidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(btnCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempoViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnCalcular))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        JTextField[] txtFields = {
            txtAutonomia, txtTempoViagem, txtValorComb, txtVelocidade
        };
        if (!verificarVazio())return;
        if (!verificarValores(txtFields))return;
        
        
        viagem2 viagem = new viagem2();
        
        viagem.setAutonomia(Double.parseDouble(txtAutonomia.getText()));
        viagem.setValorComb(Double.parseDouble(txtValorComb.getText()));
        viagem.setTempoViagem(Integer.parseInt(txtTempoViagem.getText()));
        viagem.setVelocidade(Double.parseDouble(txtVelocidade.getText()));
        
        String saida = viagem.calcular();
        
        JOptionPane.showMessageDialog(null, viagem.calcular());
 
        txtAutonomia.requestFocus();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAutonomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutonomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutonomiaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtAutonomia.setText("");
        txtTempoViagem.setText("");
        txtValorComb.setText("");
        txtVelocidade.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed
    
    private boolean verificarVazio(){
        if (txtAutonomia.getText(). trim(). length() == 0 ){
            JOptionPane.showMessageDialog(null,"Forneça a autonomia");
            txtAutonomia.requestFocus();
            return false;
        }
        if (txtTempoViagem.getText(). trim(). length() == 0 ){
            JOptionPane.showMessageDialog(null,"Forneça o tempo de viagem");
            txtTempoViagem.requestFocus();
            return false;
        }
        if (txtValorComb.getText(). trim(). length() == 0 ){
            JOptionPane.showMessageDialog(null,"Forneça o valor do combustivel");
            txtValorComb.requestFocus();
            return false;
        }
        if (txtVelocidade.getText(). trim(). length() == 0 ){
            JOptionPane.showMessageDialog(null,"Forneça a velocidade");
            txtVelocidade.requestFocus();
            return false;
        }
        return true;
    }
    private boolean verificarValores(JTextField[] txtFields){
        int errorCounter = 0;
        for (int i=0; i < txtFields.length; i++){
            try {
                Double.parseDouble(txtFields[i].getText());
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, " O valor " + txtFields[i].getText() + "Não é um numero!");
                txtFields[i].setText("");
                errorCounter++;
        }    
    }
        return errorCounter == 0;
  }     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAutonomia;
    private javax.swing.JTextField txtTempoViagem;
    private javax.swing.JTextField txtValorComb;
    private javax.swing.JTextField txtVelocidade;
    // End of variables declaration//GEN-END:variables
}
